import { BudgetEngine, BudgetSummary } from '../financial/BudgetEngine';
import OpenAI from 'openai'; // or your existing AI provider setup

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export class FinancialDecisionEngine {
  /**
   * Generates a strict, read-only AI financial insight based purely on the 
   * authoritative mathematical data generated by the BudgetEngine.
   * The AI cannot modify, invent, or hallucinate financial transactions.
   */
  static async getDailyAdvisoryInsight(userId: string): Promise<string> {
    // 1. Fetch the exact, authoritative ledger calculation
    const budgetSummary: BudgetSummary = await BudgetEngine.calculateBudgetStatus(userId);
    
    // 2. Format a highly restrictive system prompt to keep the AI in its lane
    const systemPrompt = `
You are VicCalary's Financial Advisor AI. 
Your ONLY job is to provide a brief, actionable financial insight based strictly on the provided mathematical summary.

RULES:
1. DO NOT invent, hallucinate, or assume any transactions or prices.
2. DO NOT attempt to execute database commands or modify the user's budget.
3. Reference the exact remaining budget and provide a helpful, encouraging recommendation (e.g., whether they should avoid non-essential spending today).
4. Keep the response to 1-2 concise paragraphs.
`;

    const userData = `
User Financial State:
- Currency: ${budgetSummary.currency}
- Daily Limit: ${budgetSummary.recommendedDailySpend}
- Spent Today: ${budgetSummary.spentToday}
- Remaining: ${budgetSummary.remainingToday}
- Category Breakdown: ${JSON.stringify(budgetSummary.status)}
`;

    try {
      const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userData }
        ],
        temperature: 0.3, // Low temperature for factual, analytical consistency
      });

      return response.choices[0]?.message?.content || "Your budget looks healthy. Keep tracking your expenses!";
    } catch (error) {
      console.error("[FinancialDecisionEngine] AI Generation failed:", error);
      return "Unable to generate financial insights at this time. Please check your budget summary.";
    }
  }
}
